Models/data/entities/comments/Comment.cs
using SaYMemos.Models.data.entities.memos;
using SaYMemos.Models.data.entities.users;
using System.ComponentModel.DataAnnotations;
namespace SaYMemos.Models.data.entities.comments
{
    public class Comment
    {


        [Key]
        public Guid Id { get; private set; }
        public Guid MemoId { get; private set; }
        public long AuthorId { get; private set; }
        public Guid? ParentCommentId { get; private set; }
        public string Text { get; private set; }
        public DateTime LeavingDate { get; private set; }
        public Comment(Guid id, Guid memoId, long authorId, Guid? parentCommentId, string text, DateTime leavingDate)
        {
            Id = id;
            MemoId = memoId;
            AuthorId = authorId;
            ParentCommentId = parentCommentId;
            Text = text;
            LeavingDate = leavingDate;
        }
        public static Comment CreateNew(Guid memoId, long authorId, Guid? parentCommentId, string text) =>
            new(new(), memoId, authorId, parentCommentId, text, DateTime.UtcNow);
        public virtual Memo Memo { get; set; }
        public virtual User Author { get; set; }
        public virtual Comment ParentComment { get; set; }
        public virtual ICollection<Comment> ChildComments { get; set; } = new HashSet<Comment>();
        public virtual ICollection<CommentRating> Ratings { get; set; } = new HashSet<CommentRating>();

        public int CalculateTotalRating() =>
            Ratings.Count(r => r.IsUp) - Ratings.Count(r => !r.IsUp);

    }
}

Models/data/entities/comments/CommentRating.cs
using SaYMemos.Models.data.entities.users;
using System.ComponentModel.DataAnnotations;

namespace SaYMemos.Models.data.entities.comments
{
    public class CommentRating
    {


        [Key]
        public Guid Id { get; private set; }
        public Guid CommentId { get; private set; }
        public long UserId { get; private set; }
        public bool IsUp { get; private set; }
        public void ChangeIsUp()=>
            IsUp = !IsUp;
        public static CommentRating CreateNew(Guid commentId, long userId, bool isUp)
        {
            return new CommentRating
            {
                Id = Guid.NewGuid(),
                CommentId = commentId,
                UserId = userId,
                IsUp = isUp
            };
        }
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }

}

Models/data/entities/memos/Comment.cs
namespace SaYMemos.Models.data.entities.memos
{
    public record class Comment(
        Guid id, 
        Guid memoId,
        long authorId,
        Guid? parentComment,
        string text

        
        )
    {
    }
}

Models/form_classes/CommentReplyForm.cs
using SaYMemos.Models.data.entities.comments;
using SaYMemos.Models.data.entities.users;

namespace SaYMemos.Models.form_classes
{
    public record class CommentReplyForm(
        string userProfilePicture,
        string userNickname,
        string userToReply,
        string messageToReplyPreview,
        string parentCommentId,
        string text,
        string errorLine
        )

    {
        public Guid? ParentCommentGuid() =>
            Guid.TryParse(parentCommentId, out Guid commentGuid) ? commentGuid : null;
        public bool AnyError() =>
           !string.IsNullOrEmpty(errorLine);
        public CommentReplyForm Validate() =>
            (ParentCommentGuid() is null) ? this with { errorLine = "Unknown comment" } :
            string.IsNullOrWhiteSpace(text) ? this with { errorLine = "You cannot leave an empty comment" } :
            this with { errorLine = string.Empty };
        public static CommentReplyForm CreateNew(User replyingUser, Comment parentComment) =>
           new(replyingUser.ProfilePicturePath,replyingUser.Nickname, parentComment.Author.Nickname,parentComment.Text.Length<20? parentComment.Text: parentComment.Text.Substring(0,18)+"...", parentComment.Id.ToString(), string.Empty, string.Empty);

    }

}

Models/view_models/memos/CommentRatingZoneViewModel.cs
namespace SaYMemos.Models.view_models.memos
{
    public record class CommentRatingZoneViewModel(
        bool isRated,
        bool? isUp,
        string commentId,
        int rating
        );
}

Models/view_models/memos/FullInfoLikeAreaViewModel.cs
namespace SaYMemos.Models.view_models.memos
{
    public record FullInfoLikeAreaViewModel(string memoId, bool isLikedAfter, int likesCount);
}

Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Mvc;
using SaYMemos.Controllers.Helpers;
using SaYMemos.Models.form_classes;
using SaYMemos.Services.interfaces;
using ILogger = SaYMemos.Services.interfaces.ILogger;

namespace SaYMemos.Controllers
{
    public class AuthorizationController : Controller
    {
        IDatabase _db { get; init; }
        ILogger _logger { get; init; }
        IEncryptor _enc { get; init; }
        public AuthorizationController(IDatabase db, ILogger logger, IEncryptor encryptor)
        {
            _db = db;
            _logger = logger;
            _enc = encryptor;
        }
        public IActionResult Index()
        {
            if (this.GetUserId(_enc.DecryptId) == -1)
                return View(new AuthorizationForm());
            return RedirectToAction("index", "account");
         
        }
        [HttpPost]
        public async Task<IActionResult> LogInAsync(AuthorizationForm form)
        {
            if (!form.IsFormFilled())
                return PartialView(viewName: "Index", form.WithError("Fill all fields"));
            if (!_db.IsEmailTaken(form.Email))
                return PartialView(viewName: "Index", form.WithError("Unregistered email"));
            string? passwordHash = await _db.GetPasswordHashForEmail(form.Email);
            if (string.IsNullOrWhiteSpace(passwordHash))
                return PartialView(viewName: "Index", form.WithError("Unknown user"));
            string password = _enc.DecryptPassword(passwordHash);
            if (form.Password != password)
                return PartialView(viewName: "Index", form.WithError("Invalid password"));

            long? userId = await _db.GetUserIdByEmail(form.Email);
            if (userId is null)
                return PartialView(viewName: "Index", form.WithError("Invalid password"));
            this.SetUserId( (long)userId, _enc.EncryptId);
            await _db.UpdateLastLoginDateForUser((long)userId);
            _logger.Info($"User with id {userId} has logged in");
            return RedirectToAction("Index", controllerName: "Account");
        }
    }
}

Controllers/MemoInteractionController.cs
using Microsoft.AspNetCore.Mvc;
using SaYMemos.Controllers.Helpers;
using SaYMemos.Models.data.entities.comments;
using SaYMemos.Models.data.entities.memos;
using SaYMemos.Models.data.entities.users;
using SaYMemos.Models.form_classes;
using SaYMemos.Models.view_models.memos;
using SaYMemos.Services.interfaces;
using ILogger = SaYMemos.Services.interfaces.ILogger;

namespace SaYMemos.Controllers
{
    public class MemoInteractionController : Controller
    {
        IDatabase _db { get; init; }
        ILogger _logger { get; init; }
        IEncryptor _enc { get; init; }
        public MemoInteractionController(IDatabase db, ILogger logger, IEncryptor enc)
        {
            _db = db;
            _logger = logger;
            _enc = enc;
        }

        [HttpPost]
        public async Task<IActionResult> LikePressed(string memoId)
        {

            if (!Guid.TryParse(memoId, out Guid parsedMemoId))
                return BadRequest("Invalid Memo ID format.");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            await _db.UpdateLastLoginDateForUser(user);

            bool isLikedAfter = await _db.ChangeLikeState(user, parsedMemoId);
            return PartialView(viewName: "LikeIcon", new MemoLikeViewModel(isLikedAfter, memoId));
        }


        [HttpPost]
        public async Task<IActionResult> LeaveComment(string memoId, string commentText)
        {

            if (!Guid.TryParse(memoId, out Guid parsedMemoId))
                return BadRequest("Invalid Memo ID format");
            if (string.IsNullOrEmpty(commentText))
                return BadRequest("Invalid comment");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();
            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            await _db.UpdateLastLoginDateForUser(userId);


            Comment? addedComment = await _db.AddCommentToMemo(parsedMemoId, commentText, user.Id);
            if (addedComment is null)
                return PartialView(viewName: "CommentForm", CommentFormViewModel.Error(parsedMemoId));

            return PartialView(viewName: "CommentForm", CommentFormViewModel.Success(addedComment.Id, parsedMemoId));
        }
        [HttpPost]
        public async Task<IActionResult> RenderAddedComment(string commentId)
        {

            if (!Guid.TryParse(commentId, out Guid commentGuid))
                return BadRequest("Invalid ID");
            Comment? comment = await _db.GetCommentById(commentGuid);
            if (comment is null)
                return BadRequest("Unknown comment");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return PartialView(viewName: "AddedComment", CommentViewModel.FromCommentForUnauthorized(comment));

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return PartialView(viewName: "AddedComment", CommentViewModel.FromCommentForUnauthorized(comment));

            await _db.UpdateLastLoginDateForUser(userId);

            return PartialView(viewName: "AddedComment", CommentViewModel.FromCommentForUser(comment, user));
        }

        [HttpPost]
        public async Task<IActionResult> RenderAllMemoInfo(string memoId)
        {
            if (!Guid.TryParse(memoId, out Guid parsedMemoId))
                return BadRequest("Invalid Memo ID format.");

            Memo? memo = await _db.GetMemoById(parsedMemoId);
            if (memo is null)
                return BadRequest("Unknown Memo");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return PartialView(viewName: "FullMemoInfo", model: MemoFullInfoViewModel.FromMemoForUnauthorized(memo));

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return PartialView(viewName: "FullMemoInfo", model: MemoFullInfoViewModel.FromMemoForUnauthorized(memo));

            await _db.UpdateLastLoginDateForUser(userId);
            return PartialView(viewName: "FullMemoInfo", model: MemoFullInfoViewModel.FromMemoForUser(memo, user));
        }
        [HttpPost]
        public async Task<IActionResult> RenderTags(string memoId)
        {
            if (!Guid.TryParse(memoId, out Guid parsedMemoId))
                return BadRequest("Invalid Memo ID format.");

            Memo? memo = await _db.GetMemoById(parsedMemoId);
            if (memo is null)
                return BadRequest("Unknown Memo");

            return PartialView(viewName: "TagsZone", model: memo.Tags.Select(t => t.Value));
        }
        [HttpPost]
        public async Task<IActionResult> RateComment(string commentId, bool isUp)
        {
            if (!Guid.TryParse(commentId, out Guid commentGuid))
                return BadRequest("Invalid comment ID format.");

            Comment? comment = await _db.GetCommentById(commentGuid);
            if (comment is null)
                return BadRequest("Unknown comment");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            await _db.UpdateLastLoginDateForUser(user);

            (bool isRatedAfter, bool? isUpAfter) = await _db.ChangeCommentRatingByUser(comment, user, isUp);

            return PartialView(viewName: "CommentRatingZone", model: new CommentRatingZoneViewModel(isRatedAfter, isUpAfter, commentId, comment.CalculateTotalRating()));
        }
        [HttpPost]
        public async Task<IActionResult> RenderCommentReplyForm(string commentId)
        {
            if (!Guid.TryParse(commentId, out Guid commentGuid))
                return BadRequest("Invalid comment ID format");

            var Comment = await _db.GetCommentById(commentGuid);
            if (Comment is null)
                return BadRequest("Unknown comment");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            return PartialView(
                viewName: "CommentReplyForm",
                model: CommentReplyForm.CreateNew(user, Comment));
        }
        [HttpPost]
        public async Task<IActionResult> SaveReplyComment(CommentReplyForm form)
        {
            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            await _db.UpdateLastLoginDateForUser(userId);

            form = form.Validate();
            if (form.AnyError())
                return PartialView(viewName: "CommentReplyForm", form);

            var parentComment = await _db.GetCommentById((Guid)form.ParentCommentGuid());
            if (parentComment is null)
                return PartialView(viewName: "CommentReplyForm", form with { errorLine = "Unknown comment" });
            Comment? newComment = await _db.AddCommentToMemo(parentComment.MemoId, form.text, user.Id, parentComment.Id);
            if (newComment is null)
                return PartialView(viewName: "CommentReplyForm", form with { errorLine = "Error during comment saving. Please try again later" });

            return PartialView(viewName: "ReplyCommentAdded", model: (parentComment.Id.ToString(), CommentViewModel.FromCommentForUser(newComment, user)));
        }
        [HttpPost]
        public async Task<IActionResult> RefreshBottomInfo(string commentId)
        {
            if (!Guid.TryParse(commentId, out Guid commentGuid))
                return BadRequest("Invalid comment ID format");

            var Comment = await _db.GetCommentById(commentGuid);
            if (Comment is null)
                return BadRequest("Unknown comment");
            return PartialView(viewName: "CommentBottomInfo", model: (commentId, Comment.ChildComments.Count(), Comment.Ratings.Count));
        }
        [HttpPost]
        public async Task<IActionResult> FullInfoLikePressed(string memoId)
        {
            if (!Guid.TryParse(memoId, out Guid parsedMemoId))
                return BadRequest("Invalid Memo ID format.");
            var memo = await _db.GetMemoById(parsedMemoId);
            if (memo is null)
                return  BadRequest("Unknown memo");

            long userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return this.HxUnauthorized();

            User? user = await _db.GetUserById(userId);
            if (user is null)
                return this.HxUnauthorized();

            await _db.UpdateLastLoginDateForUser(user);

            bool isLikedAfter = await _db.ChangeLikeState(user, parsedMemoId);
         
            return PartialView(viewName: "FullInfoLikeArea", new FullInfoLikeAreaViewModel( memoId, isLikedAfter,memo.Likes.Count ));
        }
    }
}

Views/MemoInteraction/AddedComment.cshtml
@model CommentViewModel
<comment-section comment="@Model"></comment-section>

Views/MemoInteraction/CommentBottomInfo.cshtml
@model (string commentId, int repliesCount, int ratingsCount)
<div class='comment-bottom-info' id='bi-@Model.commentId'>
    <label class='comment-bottom-label'>Replies: @Model.repliesCount</label>
    <label class='comment-bottom-label'>Ratings: @Model.ratingsCount</label>
</div>

Views/MemoInteraction/CommentForm.cshtml
@model CommentFormViewModel


<form class='memo-fu-add-comment' hx-post='MemoInteraction/LeaveComment'>
    @if (string.IsNullOrEmpty(Model.error))
    {
        <div hx-trigger="load" hx-post="/MemoInteraction/renderAddedComment?commentId=@Model.commentId" hx-target=".new-added-comments" hx-swap="afterbegin"></div>
    }
    else
    {
        <p class="error-line">@Model.error</p>
    }
    <input type='hidden' value='@Model.memoId' name='memoId' />
    <input type='text' placeholder='Add a comment...' name='commentText' />
    <button type='submit' class="post-comment-button">
        <svg viewBox="0 0 512 512">
            <path d="M16.1 260.2c-22.6 12.9-20.5 47.3 3.6 57.3L160 376V479.3c0 18.1 14.6 32.7 32.7 32.7c9.7 0 18.9-4.3 25.1-11.8l62-74.3 123.9 51.6c18.9 7.9 40.8-4.5 43.9-24.7l64-416c1.9-12.1-3.4-24.3-13.5-31.2s-23.3-7.5-34-1.4l-448 256zm52.1 25.5L409.7 90.6 190.1 336l1.2 1L68.2 285.7zM403.3 425.4L236.7 355.9 450.8 116.6 403.3 425.4z" />
        </svg>
    </button>
</form>

Views/MemoInteraction/CommentRatingZone.cshtml
@model CommentRatingZoneViewModel



@{
    HtmlString hxAtrributes(bool isUp)
    {
        string jsonParams = $"{{\"commentId\": \"{Model.commentId}\", \"isUp\": {isUp.ToString().ToLower()}}}";
        return new($"hx-vals='js:{jsonParams}' hx-redirect='/authorization' hx-trigger='click' hx-swap='outerHTML' hx-post='/MemoInteraction/RateComment' hx-target='#mr-{Model.commentId}' ");
    }

    HtmlString iconFilledPath = new(@"<path d=""M4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625l-8-10c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14z"" />");
    HtmlString iconPath = new(@"<path d=""M12.781 2.375c-.381-.475-1.181-.475-1.562 0l-8 10A1.001 1.001 0 0 0 4 14h4v7a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-7h4a1.001 1.001 0 0 0 .781-1.625l-8-10zM15 12h-1v8h-4v-8H6.081L12 4.601 17.919 12H15z""/>");
}

<div class='comment-meta-right' id='mr-@Model.commentId' hx-trigger="load" hx-post="/MemoInteraction/refreshBottomInfo?commentId=@Model.commentId" hx-target="#bi-@Model.commentId" hx-swap="outerHTML">
    <span class='comment-rating'>@Model.rating</span>
    <div class="comment-rating-buttons">
        @if (!Model.isRated)
        {
            <span class="comment-rating-button" @hxAtrributes(true)>
                <svg viewBox="0 0 24 24">
                    @iconPath
                </svg>
            </span>

            <span class="comment-rating-button" @hxAtrributes(false)>
                <svg viewBox="0 0 24 24" style='transform: scaleY(-1);'>
                    @iconPath
                </svg>
            </span>

        }
        else
        {
            @if ((bool)Model.isUp)
            {
                <span class="comment-rating-button" @hxAtrributes(true)>
                    <svg viewBox="0 0 24 24">
                        @iconFilledPath
                    </svg>
                </span>

                <span class="comment-rating-button" @hxAtrributes(false)>
                    <svg viewBox="0 0 24 24" style='transform: scaleY(-1);'>
                        @iconPath
                    </svg>
                </span>
            }
            else
            {
                <span class="comment-rating-button" @hxAtrributes(true)>
                    <svg viewBox="0 0 24 24">
                        @iconPath
                    </svg>
                </span>

                <span class="comment-rating-button" @hxAtrributes(false)>
                    <svg viewBox="0 0 24 24" style='transform: scaleY(-1);'>
                        @iconFilledPath
                    </svg>
                </span>
            }
        }
    </div>

</div>

Views/MemoInteraction/FullMemoInfo.cshtml
@model MemoFullInfoViewModel



<div class="memo-top-border">
    <button class="close-button" onclick="closeMemoFullInfo()">
        <span>&times;</span>
    </button>
</div>

<div class="memo-fu-container">
    <div class="memo-fu-main">
        <a href='/account?userId=@Model.authorId' class="memo-fu-author">
            <img src='@Model.authorProfilePicture' alt='Profile Picture' />
            <span>@Model.authorNickName</span>
        </a>

        @if (!string.IsNullOrEmpty(Model.imagePath))
        {
            <div class="memo-fu-image">
                <img src="@Model.imagePath" alt="Memo Image">
            </div>
        }

        <div class="memo-fu-author-comment">
            <p>@Model.authorComment</p>
        </div>

        <div class="memo-fu-likes-footer">
            <span hx-trigger='click' hx-redirect='/authorization' hx-post='MemoInteraction/FullInfoLikePressed' hx-target='.memo-fu-likes-footer' hx-swap='outerHTML' hx-vals='{"memoId": "@Model.id"}'
                  class='@(Model.isLiked ? "memo-like-pressed" : "memo-icon")'>
                <svg viewBox="0 0 512 512">
                    @if (Model.isLiked)
                    {
                        <path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z" />
                    }
                    else
                    {
                        <path d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z" />
                    }
                </svg>

            </span>
            <label class="likes">Likes: @Model.likesCount</label>
        </div>

        <div class="memo-tags">
            @foreach (string tag in Model.tags)
            {
                <memo-tag tagName="@tag"></memo-tag>
            }
            @if (Model.tags.Length == 10)
            {
                <button class="see-all-tags" hx-trigger="click" hx-post="/MemoInteraction/RenderTags?memoId=@Model.id" hx-swap="OuterHTML" hx-target=".memo-tags">See all tags...</button>
            }
        </div>

    </div>
    @if (Model.areCommentsAvaliable)
    {
        <div class="memo-fu-sidebar">

            <div class="memo-fu-comments">
                <label class="memo-comments-count">Comments: @Model.comments.Length</label>
                <div class="new-added-comments"></div>
                @foreach (var comment in Model.comments)
                {
                    <comment-section comment="comment"></comment-section>
                }
            </div>
            @if (Model.isViewerAuthorized)
            {
                <form class='memo-fu-add-comment' hx-post='MemoInteraction/LeaveComment' hx-target='this' hx-swap="outerHTML">
                    <input type='hidden' value='@Model.id' name='memoId' />
                    <input type='text' placeholder='Add a comment...' name='commentText' />
                    <button type='submit' class="post-comment-button">
                        <svg viewBox="0 0 512 512">
                            <path d="M16.1 260.2c-22.6 12.9-20.5 47.3 3.6 57.3L160 376V479.3c0 18.1 14.6 32.7 32.7 32.7c9.7 0 18.9-4.3 25.1-11.8l62-74.3 123.9 51.6c18.9 7.9 40.8-4.5 43.9-24.7l64-416c1.9-12.1-3.4-24.3-13.5-31.2s-23.3-7.5-34-1.4l-448 256zm52.1 25.5L409.7 90.6 190.1 336l1.2 1L68.2 285.7zM403.3 425.4L236.7 355.9 450.8 116.6 403.3 425.4z" />
                        </svg>

                    </button>
                </form>
            }
            else
            {
                <a asp-action="Index" asp-controller="Authorization" class="unauthorized-label">Log in to leave comments</a>
            }
        </div>
    }
</div>

Views/MemoInteraction/ReplyCommentAdded.cshtml
@model (string parrentCommentId, CommentViewModel newComment)
<div hx-trigger="load" hx-post="/MemoInteraction/refreshBottomInfo?commentId=@Model.parrentCommentId" hx-target="#bi-@Model.parrentCommentId" hx-swap="outerHTML"></div>
<button class='answer-button' hx-trigger='click' hx-swap='outerHTML' hx-target='this' hx-redirect='/authorization' hx-post='/MemoInteraction/RenderCommentReplyForm' hx-vals='{"commentId": "@Model.parrentCommentId"}'>Reply</button>
<comment-section comment="@Model.newComment"></comment-section>

Views/MemoInteraction/TagsZone.cshtml
@model IEnumerable<string>
<div class="memo-tags">
    @foreach (string tag in Model)
    {
        <memo-tag tagName="@tag" />
    }
</div>