Models/view_models/account/MyAccountViewModel.cs
using SaYMemos.Models.data.entities.users;
using SaYMemos.Models.view_models.memos;

namespace SaYMemos.Models.view_models.account
{
    public record MyAccountViewModel(
       string nickname,
       string profilePicturePath,
       Dictionary<string, string> links,
       string fullName,
       MemoPreviewViewModel[] memos
       )
    {
        public static MyAccountViewModel FromUser(User user)
        {
            var likedMemoIds = user.Likes.Select(l => l.MemoId).ToHashSet();

            return new MyAccountViewModel(
                user.Nickname,
                user.ProfilePicturePath,
                user.UserLinks.ParseToNonEmptyDictionary(),
                user.FullName,
                user.PostedMemos
                    .Select(memo => MemoPreviewViewModel.FromMemo(memo, user))
                    .OrderByDescending(memo => memo.creationDate)
                    .ToArray()
            );
        }


    }

}

Controllers/MyAccountController.cs
using Microsoft.AspNetCore.Mvc;
using SaYMemos.Controllers.Helpers;
using SaYMemos.Models.data.entities.users;
using SaYMemos.Models.form_classes;
using SaYMemos.Models.view_models.account;
using SaYMemos.Services.interfaces;
using ILogger = SaYMemos.Services.interfaces.ILogger;

namespace SaYMemos.Controllers
{
    public class MyAccountController : Controller
    {
        IDatabase _db { get; init; }
        ILogger _logger { get; init; }
        IEncryptor _enc { get; init; }
        IImageStorageService _imgStorage { get; init; }
        public MyAccountController(IDatabase db, ILogger logger, IEncryptor encryptor, IImageStorageService imgStorage)
        {
            _db = db;
            _logger = logger;
            _enc = encryptor;
            _imgStorage = imgStorage;
        }
        public async Task<IActionResult> Index()
        {
            long? userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return Unauthorized();
            User? user = await _db.GetUserById((long)userId);
            if (user is null)
            {
               Response.RemoveUserIdCookies();
                return Unauthorized();
            }
            return View(MyAccountViewModel.FromUser(user));
        }
        [HttpPost]
        public async Task<IActionResult> Settings()
        {
            long? userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return Unauthorized();
            User? user = await _db.GetUserById((long)userId);
            if (user is null)
                return Unauthorized();

            return View(AccountSettingsForm.FromUser(user));
        }

        [HttpPost]
        public async Task<IActionResult> LogoutAsync()
        {
            long id = this.GetUserId(_enc.DecryptId);
            if (id == -1)
                return Unauthorized();
            await _db.UpdateLastLoginDateForUser(id);
            HttpContext.Response.RemoveUserIdCookies();
            _logger.Info($"User with id {id} has logged out");

            Response.Headers["HX-Redirect"] = "/authorization";
            return Ok();
        }



        [HttpPost]
        public async Task<IActionResult> SaveProfilePictureAsync(IFormFile picture)
        {
            if (picture is null || picture.Length == 0)
                return RenderProfilePictureInput("No image received");

            (string error,Stream? imageStream) =await _imgStorage.TryConvertFormImageToStream(picture);
            if (!string.IsNullOrEmpty(error))
                return RenderProfilePictureInput(error);


            long? userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1 || userId == null)
                return Unauthorized();

            User? user = await _db.GetUserById((long)userId);
            if (user is null)
                return Unauthorized();

            await _db.UpdateLastLoginDateForUser((long)userId);

            string savedImagePath= _imgStorage.SaveProfilePicture(imageStream, user.Id);


            await _db.SetProfilePictureForUser(user.Id, savedImagePath);
            return await RenderSettingsProfilePictureAsync();
        }

        [HttpPost]
        public async Task<IActionResult> SaveSettingsAsync(AccountSettingsForm form)
        {
            long id = this.GetUserId(_enc.DecryptId);
            if (id == -1)
                return Unauthorized();
            await _db.UpdateLastLoginDateForUser(id);

            var data = form.Validate();
            if (data.AnyErrors())
                return PartialView(viewName: "Settings", model: data);

            User? user = await _db.GetUserById(id);
            if (user is null)
                return Unauthorized();

            await _db.UpdateUserSettings(data, id);
            Response.Headers["HX-Redirect"] = "/MyAccount";
            return Ok();
        }

        [HttpPost]
        public IActionResult RenderProfilePictureInput(string error = "") => PartialView(viewName: "ProfilePictureInput", error);
        [HttpPost]
        public async Task<IActionResult> RenderSettingsProfilePictureAsync()
        {
            long? userId = this.GetUserId(_enc.DecryptId);
            if (userId == -1)
                return Unauthorized();
            string? picturePath = await _db.GetProfilePictureById((long)userId);
            return PartialView(viewName: "SettingsProfilePicture", picturePath);
        }
    }
}

Views/MyAccount/ProfilePictureInput.cshtml
@model string?

<form class="new-profile-picture-form" hx-post="MyAccount/SaveProfilePicture" hx-swap="outerHTML" enctype="multipart/form-data">

    <input type="file" name="picture" id="newProfilePicture" class="new-profile-picture-input" accept=".jpg, .jpeg, .png" required />
    <label for="newProfilePicture" class="file-upload-label"></label>

    <p class="error-line">@Model</p>
    <div class="new-prof-pic-buttons">
        <button type="button" hx-post="/myAccount/renderSettingsProfilePicture" hx-trigger="click" hx-target=".new-profile-picture-form" hx-swap="outerHTML">Cancel</button>
        <input type="submit" value="Save" />
    </div>
</form>

Views/MyAccount/Settings.cshtml
@using Microsoft.AspNetCore.Html
@model AccountSettingsForm



<form class='account-settings-container @(Model.AnyErrors() ? "form-error-borders" : "")' hx-post="MyAccount/SaveSettings" hx-swap="outerHTML" hx-redirect="/MyAccount">

    <link rel="stylesheet" href="~/css/pages/account/settings/profile_picture.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/pages/account/settings/settings.css" asp-append-version="true" />

    <div class="settings-area">
        <p class="settings-area-header">Main</p>
        <div class="main-area-content">
            <div hx-post="/MyAccount/RenderSettingsProfilePicture" hx-target="this" hx-trigger="load">Unable to load profile picture</div>
            <div class="main-area-inputs">
                <p class="main-area-input-line">
                    Nickname:
                    <input type="text" asp-for="@Model.nickname" required />
                </p>
                <p class="main-area-input-line">
                    Full Name:
                    <input type="text" asp-for="@Model.fullName" />
                </p>
            </div>
        </div>

        @AddErrorLineIfNeeded(Model.mainFieldError)
    </div>

    <div class="settings-area">
        <p class="settings-area-header">Privacy</p>
        <p class="privacy-input">
            Is Account Private
            <input type="checkbox" class="default-checkbox" asp-for="isAccountPrivate" />
        </p>
        <p class="privacy-input">
            Are Links Private
            <input type="checkbox" class="default-checkbox" asp-for="areLinksPrivate"  />
        </p>
        <p class="privacy-input">
            Is Last Login Date Private
            <input type="checkbox" class="default-checkbox" asp-for="isLastLoginDatePrivate"  />
        </p>
    </div>

    <div class="settings-area">
        <p class="settings-area-header">Links</p>
        <p class="link-input-line">
            GitHub:
            <input type="text" asp-for="@Model.githubLink" />
        </p>
        <p class="link-input-line">
            Telegram:
            <input type="text" asp-for="@Model.telegramLink" />
        </p>
        <p class="link-input-line">
            YouTube:
            <input type="text" asp-for="@Model.youtubeLink" />
        </p> <p class="link-input-line">
            Discord:
            <input type="text" asp-for="@Model.discordLink" />
        </p>
        @AddErrorLineIfNeeded(Model.linksFieldError)
    </div>

    <div class="settings-area">
        <p class="settings-area-header">Additional info</p>
        <label>About me:</label>
        <textarea class="additional-info-textarea" asp-for="@Model.aboutMe"></textarea>
        <label>Hobbies:</label>
        <textarea class="hobbies-textarea" asp-for="@Model.hobbies"></textarea>

        @AddErrorLineIfNeeded(Model.additionalInfoFieldError)
    </div>

    <div class="buttons-container">
        <a class="cancel-button" asp-action="Index" asp-controller="MyAccount">Cancel and close</a>
        <input class="save-button" type="submit" value="Save and close" />
    </div>
</form>

@{
    HtmlString AddErrorLineIfNeeded(string fieldName) =>
        !string.IsNullOrEmpty(fieldName)
            ? new HtmlString($"<p class=\"error-line\">{fieldName}</p>")
            : new HtmlString(string.Empty);
}

Views/MyAccount/SettingsProfilePicture.cshtml
@model string
@{
    var ProfilePicture = Model;
}
<div class="profile-picture-container">
    @if (string.IsNullOrEmpty(ProfilePicture))
    {
        <div class="no-picture-found">
            No profile picture found
        </div>
    }
    else
    {
        <img src="/@($"{ProfilePicture}?{DateTime.UtcNow.Ticks}")" class="profile-picture" />

    }
    <button hx-post="/myAccount/renderProfilePictureInput" hx-trigger="click" hx-target=".profile-picture-container" hx-swap="outerHTML">
        Choose new profile picture
    </button>
</div>